<?php

/**
 * @file
 * Contains simple_json_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_json_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_json_api module.
    case 'help.page.simple_json_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Json API simple') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function simple_json_api_preprocess_page(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();

  if($current_path == "/devel/php"){
//      $t = Drupal::configFactory()->listAll();
//      $tr =[];
//      $helper = \Drupal::service('drupal.helper');
//      foreach ($t as $cong){
//          if (strpos($cong, 'header_1v1') !== false) {
//              $tr[] = $cong ;
//          }
//      }
//      kint($tr);

//      $order_json = \Drupal::service('order_json');
//      $json = $order_json->getItems('orders','');
//      $orders = \Drupal\Component\Serialization\Json::decode($json);
//      if(!empty($orders)){
//          foreach ($orders as $order){
//              $status = $order_json->importOrder($order);
//              $message = 'Successfull import order from json status = '.$status ;
//              \Drupal::logger("server_json")->info($message);
//          }
//      }
//
//      $node = \Drupal::entityTypeManager()->getStorage('node')->load(30542);
//      $prods = \Drupal::service('entity_parser.manager')->parser($node);
//      $parser_node_json = \Drupal::service('product_json');
//      $status = $parser_node_json->insertAPIProduit($prods);

//      $fields = [
//          'field_prix_vente' => '1',
//          'field_typ' =>'524',
//          'field_total' => 0,
//      ];
//      $paragraph = \Drupal::service('crud')->save('paragraph', 'field_autre_prix_de_vente', $fields);
//      kint($paragraph);
  //    $node = \Drupal::entityTypeManager()->getStorage('node')->load(30494);
  //    $jsonservcie = \Drupal::service('order_json');
  //    $items = $jsonservcie->itemApiOrder($node);
  //    kint($items);
   //   die();
   /// $id =  28859 ;
   // var_dump($id);
   // $produit = \Drupal::service('entity_parser.manager')->node_parser($id);
   // kint($produit);
    //  $field_users = array(
    //   'name' => 'mm-'.rand(),
    //   'mail' => 'mobile@mobile.com',
    //   'pass' => 'password',
    //   'status' => 0,
    //   'field_adresse' => [
    //     [ 'field_adress' => 'Test',
    //        'field_email' =>'@',
    //        'field_phone' => '1231'

    //     ]
    //   ]
    //   );
    //  $user = \Drupal::service('crud')->save('user','user',$field_users);
    //  kint($user);
  }
}
